# astype()
# Number conversion
# pd.to_numeric()
# Date conversion
# pd.to_datetime()

In [2]:
import pandas as pd

data = {
    "Employee_ID": ["101", "102", "103", "104", "105",
                    "106", "107", "108", "109", "110"],

    "Name": ["Amit", "Rahul", "Neha", "Pooja", "Rohit",
             "Sneha", "Vikas", "Kiran", "Ankit", "Priya"],

    "Age": ["25", "28", "30", "26", "32",
            "29", "27", "31", "24", "35"],

    "Salary": ["35000", "42000", "50000", "38000", "55000",
               "45000", "60000", "40000", "48000", "52000"],

    "Experience": ["2", "4", "6", "3", "8",
                    "5", "7", "4", "2", "9"],

    "Department": ["IT", "HR", "Finance", "Sales", "IT",
                   "HR", "IT", "Finance", "Sales", "IT"]
}

df = pd.DataFrame(data)
df

  Employee_ID   Name Age Salary Experience Department
0         101   Amit  25  35000          2         IT
1         102  Rahul  28  42000          4         HR
2         103   Neha  30  50000          6    Finance
3         104  Pooja  26  38000          3      Sales
4         105  Rohit  32  55000          8         IT
5         106  Sneha  29  45000          5         HR
6         107  Vikas  27  60000          7         IT
7         108  Kiran  31  40000          4    Finance
8         109  Ankit  24  48000          2      Sales
9         110  Priya  35  52000          9         IT

In [17]:
df["Age"].dtype
df["Name"].dtype
df.dtypes


df["Name"]=df["Name"].astype(str)
df["Name"].dtype
df.dtypes

df["Name"]=df["Name"].astype(str)
df.dtypes

Employee_ID    object
Name           object
Age            object
Salary         object
Experience     object
Department     object
dtype: object

In [22]:
# Age ko integer mein convert karo
df["Age"]=df["Age"].astype(int)

# Salary ko float mein convert karo
df["Salary"]=df["Salary"].astype(float)

# Experience ko integer mein convert karo
df["Experience"]=df["Experience"].astype(int)


# Employee_ID ko integer mein convert karo
df["Employee_ID"]=df["Employee_ID"].astype(int)

# Department ko category datatype mein convert karo
df["Department"]=df["Department"].astype("category")

# Age aur Experience ko ek saath integer mein convert karo
df=df.astype({
    "Experience":int,
    "Age":int
})

# Number Conversion = pd.to_numeric()

In [23]:
# pd.to_numeric() is used to convert values into numeric data.

# It can convert:
# String → Integer/Float
# Object → Numeric

# Syntax:
# pd.to_numeric(df["Column"])

# Basic numeric conversion
# pd.to_numeric(df["Salary"])

# Invalid values ko NaN mein convert karna
#pd.to_numeric(
    #df["Salary"],
    #errors="coerce" )

# Invalid value par error
#pd.to_numeric(
    #df["Salary"],
    #errors="raise")

In [36]:
import pandas as pd

data = {
    "Order_ID": [
        "1001", "1002", "1003", "1004", "1005",
        "1006", "1007", "1008", "1009", "1010"
    ],

    "Product": [
        "Laptop", "Mobile", "Tablet", "Headphone", "Monitor",
        "Keyboard", "Mouse", "Printer", "Laptop", "Mobile"
    ],

    "Quantity": [
        "2", "3", "5", "2", "4",
        "Unknown", "3", "Five", "2", "4"
    ],

    "Price": [
        "55000", "25000", "30000", "5000", "22000",
        "1500", "800", "12000", "56000", "26000"
    ],

    "Discount": [
        "10", "5", "8", "None", "10",
        "5", "Invalid", "7", "10", "None"
    ],

    "Sales": [
        "110000", "75000", "150000", "10000", "88000",
        "Invalid", "2400", "84000", "112000", "104000"
    ]
}

df = pd.DataFrame(data)
df

df.dtypes

# Q1. Order_ID column ko numeric datatype mein convert karo.

df["Order_ID"]= pd.to_numeric(df["Order_ID"])

# Q2. Quantity column ko numeric mein convert karo.
# Invalid values ko NaN mein convert karo using errors="coerce".

df["Quantity"]=pd.to_numeric(
    df["Quantity"],
    errors="coerce"
)

# Q3. Discount column ko numeric mein convert karo.
# Invalid values ko NaN mein convert karo.
df["Discount"]=pd.to_numeric(
    df["Discount"],
    errors="coerce"
)

# Q4. Sales column ko numeric mein convert karo.
# Invalid values ko NaN mein convert karo.

df["Sales"]=pd.to_numeric(
    df["Sales"],
    errors="coerce"
)

# Q5. Price aur Sales dono columns ko numeric mein convert karo.
# Invalid values ko NaN mein convert karne ke liye errors="coerce" use karo.

df["Price"] = pd.to_numeric(
    df["Price"],
    errors="coerce"
)

df["Sales"] = pd.to_numeric(
    df["Sales"],
    errors="coerce"
)

# pd.to_datetime()

In [38]:
# pd.to_datetime() is used to convert a column
# into Pandas datetime format.

# It converts date values from string/object
# into datetime format.

# Syntax:
# df["Date"] = pd.to_datetime(df["Date"])

# DATE CONVERSION
#
# pd.to_datetime()
# → String/Object date ko datetime mein convert karta hai.
#
# errors="coerce"
# → Invalid date ko NaT bana deta hai.
#
# dayfirst=True
# → Date mein day ko first value maana jata hai.
#
# .dt.year
# → Year
#
# .dt.month
# → Month
#
# .dt.day
# → Day
#
# NaT
# → Not a Time / missing datetime value

In [41]:
import pandas as pd

data = {
    "Order_ID": [1001, 1002, 1003, 1004, 1005,
                 1006, 1007, 1008, 1009, 1010],

    "Customer": [
        "Amit", "Rahul", "Neha", "Pooja", "Rohit",
        "Sneha", "Vikas", "Kiran", "Ankit", "Priya"
    ],

    "Order_Date": [
        "2025-01-15",
        "2025-02-20",
        "2025-03-10",
        "2025-04-25",
        "2025-05-18",
        "Invalid",
        "2025-07-12",
        "2025-08-30",
        "Invalid",
        "2025-10-15"
    ],

    "Joining_Date": [
        "15-01-2023",
        "20-02-2022",
        "10-03-2024",
        "25-04-2021",
        "18-05-2023",
        "12-06-2022",
        "Invalid",
        "30-08-2020",
        "15-09-2021",
        "10-10-2023"
    ],

    "Delivery_Date": [
        "2025/01/20",
        "2025/02/25",
        "2025/03/15",
        "Invalid",
        "2025/05/25",
        "2025/06/18",
        "2025/07/17",
        "Invalid",
        "2025/09/10",
        "2025/10/20"
    ]
}

df = pd.DataFrame(data)
df

   Order_ID Customer  Order_Date Joining_Date Delivery_Date
0      1001     Amit  2025-01-15   15-01-2023    2025/01/20
1      1002    Rahul  2025-02-20   20-02-2022    2025/02/25
2      1003     Neha  2025-03-10   10-03-2024    2025/03/15
3      1004    Pooja  2025-04-25   25-04-2021       Invalid
4      1005    Rohit  2025-05-18   18-05-2023    2025/05/25
5      1006    Sneha     Invalid   12-06-2022    2025/06/18
6      1007    Vikas  2025-07-12      Invalid    2025/07/17
7      1008    Kiran  2025-08-30   30-08-2020       Invalid
8      1009    Ankit     Invalid   15-09-2021    2025/09/10
9      1010    Priya  2025-10-15   10-10-2023    2025/10/20

In [66]:
# ============================================================
# Q1
# ============================================================

# Order_Date column ko datetime format mein convert karo.

df["new_order_date"]=pd.to_datetime(
    df["Order_Date"],
    errors="coerce"
)
df
# ============================================================
# Q3
# ============================================================

# Delivery_Date column ko datetime mein convert karo.

df["new_delivery_date"]=pd.to_datetime(
    df["Delivery_Date"],
    errors="coerce"
)
df
# ============================================================
# Q4
# ============================================================

# Order_Date mein invalid values ko NaT mein convert karo.
# errors="coerce" ka use karo.
df["new_order_date"]=pd.to_datetime(
    df["Order_Date"],
    errors="coerce"
)
df

# ============================================================
# Q5
# ============================================================

# Order_Date se Year ka ek new column create karo.
df["year"]=df["new_order_date"].dt.year
df
df["year"].mean()
df["year"]=df["year"].fillna(df["year"].mean())
df
# ============================================================
# Q6
# ============================================================

# Order_Date se Month ka ek new column create karo.
df["month"]=df["new_order_date"].dt.month
df
df["month"].mean()
df["month"]=df["month"].fillna(df["month"].mean())
df
# ============================================================
# Q7
# ============================================================

# Order_Date se Day ka ek new column create karo.
df["day"]=df["new_order_date"].dt.day
df
df["day"].mean()
df["day"]=df["day"].fillna(df["day"].mean())
df

# ============================================================
# Q8
# ============================================================

# Order_Date se Month_Name ka new column create karo.

df["month_name"]=df["new_order_date"].dt.month_name()
df
df["month_name"].mode()
df["month_name"]=df["month_name"].fillna(df["month_name"].mode()[0])
df
# ============================================================
# Q9
# ============================================================

# Order_Date se Day_Name ka new column create karo.
df["day_name"]=df["new_order_date"].dt.day_name()
df
df["day_name"].mode()
df["day_name"]=df["day_name"].fillna(df["day_name"].mode()[0])
df

,Order_ID,Customer,Order_Date,Joining_Date,Delivery_Date,new_order_date,new_delivery_date,year,month,day,month_name,day_name
0,1001,Amit,2025-01-15,15-01-2023,2025/01/20,2025-01-15,2025-01-20,2025.0,1.0,15.000,January,Wednesday
1,1002,Rahul,2025-02-20,20-02-2022,2025/02/25,2025-02-20,2025-02-25,2025.0,2.0,20.000,February,Thursday
2,1003,Neha,2025-03-10,10-03-2024,2025/03/15,2025-03-10,2025-03-15,2025.0,3.0,10.000,March,Monday
3,1004,Pooja,2025-04-25,25-04-2021,Invalid,2025-04-25,NaT,2025.0,4.0,25.000,April,Friday
4,1005,Rohit,2025-05-18,18-05-2023,2025/05/25,2025-05-18,2025-05-25,2025.0,5.0,18.000,May,Sunday
5,1006,Sneha,Invalid,12-06-2022,2025/06/18,NaT,2025-06-18,2025.0,5.0,18.125,April,Saturday
6,1007,Vikas,2025-07-12,Invalid,2025/07/17,2025-07-12,2025-07-17,2025.0,7.0,12.000,July,Saturday
7,1008,Kiran,2025-08-30,30-08-2020,Invalid,2025-08-30,NaT,2025.0,8.0,30.000,August,Saturday
8,1009,Ankit,Invalid,15-09-2021,2025/09/10,NaT,2025-09-10,2025.0,5.0,18.125,April,Saturday
9,1010,Priya,2025-10-15,10-10-2023,2025/10/20,2025-10-15,2025-10-20,2025.0,10.0,15.000,October,Wednesday